//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace fiveStons
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FiveStonesEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FiveStonesEntities object using the connection string found in the 'FiveStonesEntities' section of the application configuration file.
        /// </summary>
        public FiveStonesEntities() : base("name=FiveStonesEntities", "FiveStonesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FiveStonesEntities object.
        /// </summary>
        public FiveStonesEntities(string connectionString) : base(connectionString, "FiveStonesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FiveStonesEntities object.
        /// </summary>
        public FiveStonesEntities(EntityConnection connection) : base(connection, "FiveStonesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Player> Players
        {
            get
            {
                if ((_Players == null))
                {
                    _Players = base.CreateObjectSet<Player>("Players");
                }
                return _Players;
            }
        }
        private ObjectSet<Player> _Players;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Log> Log
        {
            get
            {
                if ((_Log == null))
                {
                    _Log = base.CreateObjectSet<Log>("Log");
                }
                return _Log;
            }
        }
        private ObjectSet<Log> _Log;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Players EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPlayers(Player player)
        {
            base.AddObject("Players", player);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Log EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLog(Log log)
        {
            base.AddObject("Log", log);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Log")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Log : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Log object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="event_time">Initial value of the event_time property.</param>
        /// <param name="event_desc">Initial value of the event_desc property.</param>
        public static Log CreateLog(global::System.Int32 id, global::System.DateTime event_time, global::System.String event_desc)
        {
            Log log = new Log();
            log.id = id;
            log.event_time = event_time;
            log.event_desc = event_desc;
            return log;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime event_time
        {
            get
            {
                return _event_time;
            }
            set
            {
                Onevent_timeChanging(value);
                ReportPropertyChanging("event_time");
                _event_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("event_time");
                Onevent_timeChanged();
            }
        }
        private global::System.DateTime _event_time;
        partial void Onevent_timeChanging(global::System.DateTime value);
        partial void Onevent_timeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String event_desc
        {
            get
            {
                return _event_desc;
            }
            set
            {
                Onevent_descChanging(value);
                ReportPropertyChanging("event_desc");
                _event_desc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("event_desc");
                Onevent_descChanged();
            }
        }
        private global::System.String _event_desc;
        partial void Onevent_descChanging(global::System.String value);
        partial void Onevent_descChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Player")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Player : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Player object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Player CreatePlayer(global::System.Int32 id)
        {
            Player player = new Player();
            player.id = id;
            return player;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pas
        {
            get
            {
                return _pas;
            }
            set
            {
                OnpasChanging(value);
                ReportPropertyChanging("pas");
                _pas = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pas");
                OnpasChanged();
            }
        }
        private global::System.String _pas;
        partial void OnpasChanging(global::System.String value);
        partial void OnpasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> vin_count
        {
            get
            {
                return _vin_count;
            }
            set
            {
                Onvin_countChanging(value);
                ReportPropertyChanging("vin_count");
                _vin_count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vin_count");
                Onvin_countChanged();
            }
        }
        private Nullable<global::System.Int32> _vin_count;
        partial void Onvin_countChanging(Nullable<global::System.Int32> value);
        partial void Onvin_countChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> lose_count
        {
            get
            {
                return _lose_count;
            }
            set
            {
                Onlose_countChanging(value);
                ReportPropertyChanging("lose_count");
                _lose_count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lose_count");
                Onlose_countChanged();
            }
        }
        private Nullable<global::System.Int32> _lose_count;
        partial void Onlose_countChanging(Nullable<global::System.Int32> value);
        partial void Onlose_countChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> logged_on
        {
            get
            {
                return _logged_on;
            }
            set
            {
                Onlogged_onChanging(value);
                ReportPropertyChanging("logged_on");
                _logged_on = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("logged_on");
                Onlogged_onChanged();
            }
        }
        private Nullable<global::System.Boolean> _logged_on;
        partial void Onlogged_onChanging(Nullable<global::System.Boolean> value);
        partial void Onlogged_onChanged();

        #endregion
    
    }

    #endregion
    
}
